language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.11.14
  - DJANGO_VERSION=2.0.7
  - DJANGO_VERSION=2.1.7
matrix:
  exclude:
  - python: 2.7
    env: DJANGO_VERSION=2.0.7
  - python: 2.7
    env: DJANGO_VERSION=2.1.7
  - python: 3.4
    env: DJANGO_VERSION=2.1.7
install: "pip install -q psycopg2 Django==$DJANGO_VERSION djangorestframework==3.8.2"
script: ./tests/runtests.py